apiVersion: nutc.worker.com/v1beta1
kind: Worker
metadata:
  name: bs-worker
spec:
  name: bs
  assigner: "Teacher Chen"
  tasks:
    - "Learning DL/ML..."
    - "Deploy Kubernetes HA cluster..."
    - "Deploy OpenStack HA cluster... "
    - "Backup Ceph storage..."
    - "Design i.m.a.c lab..."
    - "Help iOS Team..."
  workDay: 4
