apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: operator-role
rules:
- apiGroups:
  - apiextensions.k8s.io
  - apps
  resources:
  - customresourcedefinitions
  - deployments
  verbs:
  - get
  - list
  - watch
  - update
  - create
  - delete
- apiGroups:
  - example.io
  resources:
  - "*"
  verbs:
  - "*"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: operator-role
subjects:
- kind: ServiceAccount
  namespace: default
  name: operator
