apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: simple-device-plugin-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: device-plugin
  template:
    metadata:
      labels:
        name: device-plugin
    spec:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      hostNetwork: true
      priorityClassName: system-cluster-critical
      containers:
      - name: simple-device-plugin-ctrl
        image: kairen/simple-device-plugin:v0.3.0
        args:
        - -logtostderr
        - -v=2
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        volumeMounts:
          - name: device-plugin
            mountPath: /var/lib/kubelet/device-plugins
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
