
[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.14.0-rc.1"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.14.0-rc.1"

[[constraint]]
  name = "k8s.io/klog"
  version = "0.2.0"

[prune]
  go-tests = true
  unused-packages = true
