apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
  advertiseAddress: 192.16.35.10
  bindPort: 6443
kubernetesVersion: v1.9.2
certificatesDir: /root/.kairen/certs/
networking:
  serviceSubnet: 10.96.0.0/12
  podSubnet: 10.244.0.0/16
etcd:
  dataDir: /root/.kairen/data/
nodeName: operator
